/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab6p2_josuedejesus;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author josue
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
    }

    String persona = "";

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menu_popup = new javax.swing.JPopupMenu();
        opcion_listar = new javax.swing.JMenuItem();
        opcion_modificar = new javax.swing.JMenuItem();
        opcion_eliminar = new javax.swing.JMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jd_jugadores = new javax.swing.JDialog();
        jLabel3 = new javax.swing.JLabel();
        nombreTxt = new javax.swing.JTextField();
        apellidoTxt = new javax.swing.JTextField();
        nacionalidadTxt = new javax.swing.JTextField();
        numeroTxt = new javax.swing.JTextField();
        jugadasTxt = new javax.swing.JTextField();
        copasTxt = new javax.swing.JTextField();
        tarjetasTxt = new javax.swing.JTextField();
        contratoTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        butt_guardar = new javax.swing.JButton();
        butt_cancel = new javax.swing.JButton();
        edadTxt = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jd_entrenadores = new javax.swing.JDialog();
        jLabel13 = new javax.swing.JLabel();
        apellidoTxt1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        nacionalidadTxt1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        copasTxt1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        contratoTxt1 = new javax.swing.JTextField();
        butt_guardar1 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        butt_cancel1 = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        nombreTxt1 = new javax.swing.JTextField();
        edadTxt1 = new javax.swing.JSpinner();
        jd_preparadores = new javax.swing.JDialog();
        jLabel16 = new javax.swing.JLabel();
        apellidoTxt2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        nacionalidadTxt2 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        especialidadTxt = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        tituloTxt = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        contratoTxt2 = new javax.swing.JTextField();
        butt_guardar2 = new javax.swing.JButton();
        jLabel28 = new javax.swing.JLabel();
        butt_cancel2 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        nombreTxt2 = new javax.swing.JTextField();
        edadTxt2 = new javax.swing.JSpinner();
        jd_psicologos = new javax.swing.JDialog();
        jLabel26 = new javax.swing.JLabel();
        apellidoTxt3 = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        nacionalidadTxt3 = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        tituloTxt1 = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        idTxt1 = new javax.swing.JTextField();
        Especialidad = new javax.swing.JLabel();
        especialidadTxt1 = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        informesTxt1 = new javax.swing.JTextField();
        jLabel36 = new javax.swing.JLabel();
        atendidosTxt = new javax.swing.JTextField();
        butt_guardar3 = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        butt_cancel3 = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        nombreTxt3 = new javax.swing.JTextField();
        edadTxt3 = new javax.swing.JSpinner();
        jd_listar = new javax.swing.JDialog();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_lista = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_personas = new javax.swing.JTree();
        jLabel2 = new javax.swing.JLabel();
        cb_personas = new javax.swing.JComboBox<>();
        butt_crear = new javax.swing.JButton();

        opcion_listar.setText("Listar");
        opcion_listar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                opcion_listarMouseClicked(evt);
            }
        });
        opcion_listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opcion_listarActionPerformed(evt);
            }
        });
        menu_popup.add(opcion_listar);

        opcion_modificar.setText("Modificar");
        menu_popup.add(opcion_modificar);

        opcion_eliminar.setText("Eliminar");
        menu_popup.add(opcion_eliminar);

        jLabel1.setText("jLabel1");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setText("Jugadores");

        nacionalidadTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadTxtActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jLabel5.setText("Apellido");

        jLabel6.setText("Edad");

        jLabel7.setText("Nacionalidad");

        jLabel8.setText("Numero de jugador");

        jLabel9.setText("Partidos jugados");

        jLabel10.setText("Copas ganadas");

        jLabel11.setText("Cantidad de tarjetas");

        jLabel12.setText("Contrato");

        butt_guardar.setText("Guardar");
        butt_guardar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_guardarMouseClicked(evt);
            }
        });

        butt_cancel.setText("Cancelar");
        butt_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jd_jugadoresLayout = new javax.swing.GroupLayout(jd_jugadores.getContentPane());
        jd_jugadores.getContentPane().setLayout(jd_jugadoresLayout);
        jd_jugadoresLayout.setHorizontalGroup(
            jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jugadoresLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_jugadoresLayout.createSequentialGroup()
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jd_jugadoresLayout.createSequentialGroup()
                                .addComponent(edadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel12))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_jugadoresLayout.createSequentialGroup()
                                .addComponent(nacionalidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addComponent(jLabel11))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_jugadoresLayout.createSequentialGroup()
                                .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel10))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_jugadoresLayout.createSequentialGroup()
                                .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel9)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jugadasTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(copasTxt)
                            .addComponent(tarjetasTxt)
                            .addComponent(contratoTxt))
                        .addGap(101, 101, 101))
                    .addGroup(jd_jugadoresLayout.createSequentialGroup()
                        .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_jugadoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(270, 270, 270))
            .addGroup(jd_jugadoresLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(butt_guardar)
                .addGap(64, 64, 64)
                .addComponent(butt_cancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jd_jugadoresLayout.setVerticalGroup(
            jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_jugadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addGap(104, 104, 104)
                .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_jugadoresLayout.createSequentialGroup()
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nacionalidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(edadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_jugadoresLayout.createSequentialGroup()
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jugadasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(copasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tarjetasTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contratoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))))
                .addGap(18, 18, 18)
                .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(numeroTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 83, Short.MAX_VALUE)
                .addGroup(jd_jugadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt_guardar)
                    .addComponent(butt_cancel))
                .addGap(67, 67, 67))
        );

        jButton1.setText("jButton1");

        jLabel13.setText("Apellido");

        jLabel14.setText("Edad");

        nacionalidadTxt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadTxt1ActionPerformed(evt);
            }
        });

        jLabel15.setText("Nacionalidad");

        jLabel18.setText("Copas ganadas");

        jLabel20.setText("Contrato");

        butt_guardar1.setText("Guardar");
        butt_guardar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_guardar1MouseClicked(evt);
            }
        });
        butt_guardar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_guardar1ActionPerformed(evt);
            }
        });

        jLabel21.setText("Nombre");

        butt_cancel1.setText("Cancelar");
        butt_cancel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_cancel1MouseClicked(evt);
            }
        });
        butt_cancel1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_cancel1ActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel22.setText("Entrenadores");

        javax.swing.GroupLayout jd_entrenadoresLayout = new javax.swing.GroupLayout(jd_entrenadores.getContentPane());
        jd_entrenadores.getContentPane().setLayout(jd_entrenadoresLayout);
        jd_entrenadoresLayout.setHorizontalGroup(
            jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                .addGap(94, 94, 94)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel21)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                        .addComponent(nacionalidadTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_entrenadoresLayout.createSequentialGroup()
                        .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                                .addComponent(nombreTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(58, 58, 58)
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(copasTxt1))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jd_entrenadoresLayout.createSequentialGroup()
                                .addComponent(edadTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                                .addComponent(apellidoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(contratoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(101, 101, 101))))
            .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(butt_guardar1)
                .addGap(64, 64, 64)
                .addComponent(butt_cancel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_entrenadoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel22)
                .addGap(242, 242, 242))
        );
        jd_entrenadoresLayout.setVerticalGroup(
            jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_entrenadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(104, 104, 104)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nombreTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(copasTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18))
                .addGap(18, 18, 18)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apellidoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(contratoTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addGap(18, 18, 18)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nacionalidadTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addGap(18, 18, 18)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(edadTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(jd_entrenadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt_guardar1)
                    .addComponent(butt_cancel1))
                .addGap(67, 67, 67))
        );

        jLabel16.setText("Apellido");

        jLabel17.setText("Edad");

        nacionalidadTxt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadTxt2ActionPerformed(evt);
            }
        });

        jLabel19.setText("Nacionalidad");

        jLabel23.setText("ID");

        jLabel24.setText("Especialidad");

        jLabel25.setText("Titulo");

        jLabel27.setText("Contrato");

        butt_guardar2.setText("Guardar");
        butt_guardar2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_guardar2MouseClicked(evt);
            }
        });

        jLabel28.setText("Nombre");

        butt_cancel2.setText("Cancelar");
        butt_cancel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_cancel2MouseClicked(evt);
            }
        });
        butt_cancel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_cancel2ActionPerformed(evt);
            }
        });

        jLabel29.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel29.setText("Preparadores");

        javax.swing.GroupLayout jd_preparadoresLayout = new javax.swing.GroupLayout(jd_preparadores.getContentPane());
        jd_preparadores.getContentPane().setLayout(jd_preparadoresLayout);
        jd_preparadoresLayout.setHorizontalGroup(
            jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_preparadoresLayout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel28)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel19)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_preparadoresLayout.createSequentialGroup()
                        .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jd_preparadoresLayout.createSequentialGroup()
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apellidoTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(edadTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nacionalidadTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 127, Short.MAX_VALUE)
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel25, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(especialidadTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
                            .addComponent(tituloTxt)
                            .addComponent(contratoTxt2, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(107, 107, 107))))
            .addGroup(jd_preparadoresLayout.createSequentialGroup()
                .addGap(219, 219, 219)
                .addComponent(butt_guardar2)
                .addGap(64, 64, 64)
                .addComponent(butt_cancel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_preparadoresLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel29)
                .addGap(262, 262, 262))
        );
        jd_preparadoresLayout.setVerticalGroup(
            jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_preparadoresLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addGap(104, 104, 104)
                .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_preparadoresLayout.createSequentialGroup()
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addGap(18, 18, 18)
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidoTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(18, 18, 18)
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nacionalidadTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel19))
                        .addGap(18, 18, 18)
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(edadTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_preparadoresLayout.createSequentialGroup()
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(contratoTxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addGap(18, 18, 18)
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(especialidadTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24))
                        .addGap(18, 18, 18)
                        .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tituloTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel25))))
                .addGap(18, 18, 18)
                .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(idTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(jd_preparadoresLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt_guardar2)
                    .addComponent(butt_cancel2))
                .addGap(67, 67, 67))
        );

        jLabel26.setText("Apellido");

        jLabel30.setText("Edad");

        nacionalidadTxt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nacionalidadTxt3ActionPerformed(evt);
            }
        });

        jLabel31.setText("Nacionalidad");

        jLabel32.setText("Titulo");

        jLabel33.setText("ID");

        Especialidad.setText("Especialidad");

        jLabel35.setText("Informes");

        jLabel36.setText("Jugadores atendidos");

        butt_guardar3.setText("Guardar");
        butt_guardar3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_guardar3MouseClicked(evt);
            }
        });

        jLabel37.setText("Nombre");

        butt_cancel3.setText("Cancelar");
        butt_cancel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_cancel3MouseClicked(evt);
            }
        });
        butt_cancel3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                butt_cancel3ActionPerformed(evt);
            }
        });

        jLabel38.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel38.setText("Jugadores");

        javax.swing.GroupLayout jd_psicologosLayout = new javax.swing.GroupLayout(jd_psicologos.getContentPane());
        jd_psicologos.getContentPane().setLayout(jd_psicologosLayout);
        jd_psicologosLayout.setHorizontalGroup(
            jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_psicologosLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(butt_guardar3)
                .addGap(18, 18, 18)
                .addComponent(butt_cancel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_psicologosLayout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_psicologosLayout.createSequentialGroup()
                        .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel37)
                            .addComponent(jLabel26)
                            .addComponent(jLabel30)
                            .addComponent(jLabel31)
                            .addComponent(jLabel32))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jd_psicologosLayout.createSequentialGroup()
                                .addComponent(tituloTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(372, 372, 372))
                            .addGroup(jd_psicologosLayout.createSequentialGroup()
                                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jd_psicologosLayout.createSequentialGroup()
                                        .addComponent(edadTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70))
                                    .addComponent(nacionalidadTxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(apellidoTxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(nombreTxt3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel33, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(Especialidad, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel35, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(idTxt1)
                                    .addComponent(especialidadTxt1)
                                    .addComponent(informesTxt1)
                                    .addComponent(atendidosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(71, 71, 71))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_psicologosLayout.createSequentialGroup()
                        .addComponent(jLabel38)
                        .addGap(214, 214, 214))))
        );
        jd_psicologosLayout.setVerticalGroup(
            jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_psicologosLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel38)
                .addGap(104, 104, 104)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jd_psicologosLayout.createSequentialGroup()
                        .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nombreTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel37))
                        .addGap(18, 18, 18)
                        .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apellidoTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel26))
                        .addGap(18, 18, 18)
                        .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nacionalidadTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)
                        .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel30)
                            .addComponent(edadTxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jd_psicologosLayout.createSequentialGroup()
                        .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33))
                        .addGap(18, 18, 18)
                        .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(especialidadTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Especialidad))
                        .addGap(18, 18, 18)
                        .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(informesTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35))
                        .addGap(18, 18, 18)
                        .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(atendidosTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel36))))
                .addGap(18, 18, 18)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tituloTxt1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(jd_psicologosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(butt_guardar3)
                    .addComponent(butt_cancel3))
                .addGap(47, 47, 47))
        );

        jt_lista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Nombre", "Apellido", "Nacionalidad", "Edad", "Numero", "Partidos", "Copas", "Tarjetas"
            }
        ));
        jScrollPane2.setViewportView(jt_lista);

        javax.swing.GroupLayout jd_listarLayout = new javax.swing.GroupLayout(jd_listar.getContentPane());
        jd_listar.getContentPane().setLayout(jd_listarLayout);
        jd_listarLayout.setHorizontalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jd_listarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 581, Short.MAX_VALUE)
                .addContainerGap())
        );
        jd_listarLayout.setVerticalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jd_listarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 343, Short.MAX_VALUE)
                .addContainerGap())
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("root");
        javax.swing.tree.DefaultMutableTreeNode treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Jugadores");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Entrenadores");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Preparadores");
        treeNode1.add(treeNode2);
        treeNode2 = new javax.swing.tree.DefaultMutableTreeNode("Psicologos");
        treeNode1.add(treeNode2);
        jt_personas.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jt_personas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jt_personasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jt_personas);

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Crear");

        cb_personas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Jugadores", "Entrenadores", "Preparadores", "Psicologos" }));

        butt_crear.setText("Crear");
        butt_crear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                butt_crearMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(285, 285, 285)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(cb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(butt_crear))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 573, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(21, 21, 21)
                .addComponent(cb_personas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(butt_crear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 78, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void butt_crearMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_crearMouseClicked
        // TODO add your handling code here:
        persona = "";

        if (cb_personas.getSelectedItem().equals("Jugadores")) {
            abreJugadores();
        }
        if (cb_personas.getSelectedItem().equals("Entrenadores")) {
            abreEntrenadores();
        }
        
        if (cb_personas.getSelectedItem().equals("Preparadores")) {
            abrePreparadores();
        }
        
        if (cb_personas.getSelectedItem().equals("Psicologos")) {
            abrePsicologos();
        }
    }//GEN-LAST:event_butt_crearMouseClicked

    private void nacionalidadTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadTxtActionPerformed

    private void butt_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_cancelActionPerformed
        // TODO add your handling code here:
        jd_jugadores.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_butt_cancelActionPerformed

    private void butt_guardarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_guardarMouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_personas.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_persona;
        
        String nombre, apellido, nacionalidad;
        int edad, numero, partidos, copas, tarjetas, contrato;
        
        nombre = nombreTxt.getText();
        apellido = apellidoTxt.getText();
        nacionalidad = nacionalidadTxt.getText();
        edad = Integer.parseInt(edadTxt.getValue().toString());
        numero = Integer.parseInt(numeroTxt.getText());
        partidos = Integer.parseInt(jugadasTxt.getText());
        copas = Integer.parseInt(copasTxt.getText());
        tarjetas = Integer.parseInt(tarjetasTxt.getText());
        contrato = Integer.parseInt(contratoTxt.getText());

        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().equals(cb_personas.getSelectedItem())) {
                nodo_persona
                        = new DefaultMutableTreeNode(
                                "Jugadores");
                DefaultMutableTreeNode anio;
                anio = new DefaultMutableTreeNode(
                        new Persona(nombreTxt.getText(), apellidoTxt.getText(),
                                (String) nacionalidadTxt.getText(), (Integer) edadTxt.getValue()));

                personas.add(new Jugador(numero, partidos, copas, tarjetas, contrato, nombre, apellido, nacionalidad, edad));
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(anio);
                m.reload();
                JOptionPane.showMessageDialog(jd_jugadores, "Jugador guardado con exito");
                nombreTxt.setText("");
                apellidoTxt.setText("");
                nacionalidadTxt.setText("");
                edadTxt.setValue(20);
                numeroTxt.setText("");
                jugadasTxt.setText("");
                copasTxt.setText("");
                tarjetasTxt.setText("");
                contratoTxt.setText("");
            }
        }

    }//GEN-LAST:event_butt_guardarMouseClicked

    private void nacionalidadTxt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadTxt1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadTxt1ActionPerformed

    private void butt_guardar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_guardar1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_guardar1MouseClicked

    private void butt_cancel1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_cancel1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_cancel1ActionPerformed

    private void butt_cancel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_cancel1MouseClicked
        // TODO add your handling code here:
        jd_entrenadores.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_butt_cancel1MouseClicked

    private void butt_guardar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_guardar1ActionPerformed
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_personas.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_persona;
        
        String nombre, apellido, nacionalidad;
        int edad, numero, partidos, copas, tarjetas, contrato;
        
        nombre = nombreTxt1.getText();
        apellido = apellidoTxt1.getText();
        nacionalidad = nacionalidadTxt1.getText();
        edad = Integer.parseInt(edadTxt1.getValue().toString());
        copas = Integer.parseInt(copasTxt1.getText());
        contrato = Integer.parseInt(contratoTxt1.getText());

        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().equals(cb_personas.getSelectedItem())) {
                nodo_persona
                        = new DefaultMutableTreeNode(
                                "Jugadores");
                DefaultMutableTreeNode anio;
                anio = new DefaultMutableTreeNode(
                        new Persona(nombreTxt1.getText(), apellidoTxt1.getText(),
                                (String) nacionalidadTxt1.getText(), (Integer) edadTxt1.getValue()));

                personas.add(new Entrenador(contrato, copas, nombre, apellido, nacionalidad, edad));
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(anio);
                m.reload();
                JOptionPane.showMessageDialog(jd_entrenadores, "Entrenador guardado con exito");
                nombreTxt1.setText("");
                apellidoTxt1.setText("");
                nacionalidadTxt1.setText("");
                edadTxt1.setValue(20);
                copasTxt1.setText("");
                contratoTxt1.setText("");
            }
        }
    }//GEN-LAST:event_butt_guardar1ActionPerformed

    private void butt_cancel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_cancel2ActionPerformed
        // TODO add your handling code here:
        jd_preparadores.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_butt_cancel2ActionPerformed

    private void butt_guardar2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_guardar2MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_personas.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_persona;
        
        String nombre, apellido, nacionalidad, especialidad, titulo;
        int edad, contrato, id;
        
        nombre = nombreTxt2.getText();
        apellido = apellidoTxt2.getText();
        nacionalidad = nacionalidadTxt2.getText();
        edad = Integer.parseInt(edadTxt2.getValue().toString());
        contrato = Integer.parseInt(contratoTxt2.getText());
        id = Integer.parseInt(idTxt.getText());
        especialidad = especialidadTxt.getText();
        titulo = tituloTxt.getText();

        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().equals(cb_personas.getSelectedItem())) {
                nodo_persona
                        = new DefaultMutableTreeNode(
                                "Jugadores");
                DefaultMutableTreeNode anio;
                anio = new DefaultMutableTreeNode(
                        new Persona(nombreTxt2.getText(), apellidoTxt2.getText(),
                                (String) nacionalidadTxt2.getText(), (Integer) edadTxt2.getValue()));

                personas.add(new Preparador(id, contrato, especialidad, titulo, nombre, apellido, nacionalidad, edad));
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(anio);
                m.reload();
                JOptionPane.showMessageDialog(jd_preparadores, "Preparador guardado con exito");
                nombreTxt2.setText("");
                apellidoTxt2.setText("");
                nacionalidadTxt2.setText("");
                edadTxt2.setValue(20);
                contratoTxt2.setText("");
                idTxt.setText("");
                especialidadTxt.setText("");
                tituloTxt.setText("");
            }
        }
    }//GEN-LAST:event_butt_guardar2MouseClicked

    private void nacionalidadTxt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadTxt2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadTxt2ActionPerformed

    private void butt_cancel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_cancel2MouseClicked
        // TODO add your handling code here:
        jd_preparadores.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_butt_cancel2MouseClicked

    private void jt_personasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jt_personasMouseClicked
        // TODO add your handling code here:
        if (evt.isMetaDown()) {
            //seleccionar un nodo con click derecho
            int row = jt_personas.getClosestRowForLocation(
                    evt.getX(), evt.getY());
            jt_personas.setSelectionRow(row);
            Object v1 = jt_personas.getSelectionPath().getLastPathComponent();
            nodo_seleccionado = (DefaultMutableTreeNode) v1;

            if (nodo_seleccionado.getUserObject() instanceof Persona) {
                persona_seleccionada
                        = (Persona) nodo_seleccionado.
                                getUserObject();
                menu_popup.show(evt.getComponent(),
                        evt.getX(), evt.getY());
            }
        }
    }//GEN-LAST:event_jt_personasMouseClicked

    private void nacionalidadTxt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nacionalidadTxt3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nacionalidadTxt3ActionPerformed

    private void butt_guardar3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_guardar3MouseClicked
        // TODO add your handling code here:
        DefaultTreeModel m = (DefaultTreeModel) jt_personas.getModel();
        DefaultMutableTreeNode raiz
                = (DefaultMutableTreeNode) m.getRoot();
        DefaultMutableTreeNode nodo_persona;
        
        String nombre, apellido, nacionalidad, especialidad, titulo;
        int edad, id, informes, atendidos;
        
        nombre = nombreTxt3.getText();
        apellido = apellidoTxt3.getText();
        nacionalidad = nacionalidadTxt3.getText();
        edad = Integer.parseInt(edadTxt3.getValue().toString());
        id = Integer.parseInt(idTxt1.getText());
        especialidad = especialidadTxt1.getText();
        titulo = tituloTxt1.getText();
        informes = Integer.parseInt(informesTxt1.getText());
        atendidos = Integer.parseInt(atendidosTxt.getText());

        for (int i = 0; i < raiz.getChildCount(); i++) {
            if (raiz.getChildAt(i).toString().equals(cb_personas.getSelectedItem())) {
                nodo_persona
                        = new DefaultMutableTreeNode(
                                "Jugadores");
                DefaultMutableTreeNode anio;
                anio = new DefaultMutableTreeNode(
                        new Persona(nombreTxt2.getText(), apellidoTxt2.getText(),
                                (String) nacionalidadTxt2.getText(), (Integer) edadTxt2.getValue()));

                personas.add(new Psicologo(titulo, id, especialidad, informes, atendidos, nombre, apellido, nacionalidad, edad));
                ((DefaultMutableTreeNode) raiz.getChildAt(i)).add(anio);
                m.reload();
                JOptionPane.showMessageDialog(jd_psicologos, "Psicologo guardado con exito");
                nombreTxt3.setText("");
                apellidoTxt3.setText("");
                nacionalidadTxt3.setText("");
                edadTxt3.setValue(20);
                idTxt.setText("");
                especialidadTxt.setText("");
                tituloTxt.setText("");
                informesTxt1.setText("");
                atendidosTxt.setText("");
            }
        }
    }//GEN-LAST:event_butt_guardar3MouseClicked

    private void butt_cancel3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_butt_cancel3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_butt_cancel3ActionPerformed

    private void butt_cancel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_butt_cancel3MouseClicked
        // TODO add your handling code here:
        jd_psicologos.setVisible(false);
        this.setVisible(true);
    }//GEN-LAST:event_butt_cancel3MouseClicked

    private void opcion_listarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_opcion_listarMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_opcion_listarMouseClicked

    private void opcion_listarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opcion_listarActionPerformed
        // TODO add your handling code here:
        abreListar();
        DefaultTableModel modelo
                    = (DefaultTableModel) jt_lista.getModel();
    }//GEN-LAST:event_opcion_listarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    private void abreJugadores() {
        this.setVisible(false);
        jd_jugadores.setModal(true);
        jd_jugadores.pack();
        jd_jugadores.setLocationRelativeTo(this);
        jd_jugadores.setVisible(true);
    }
    
    private void abreEntrenadores() {
        this.setVisible(false);
        jd_entrenadores.setModal(true);
        jd_entrenadores.pack();
        jd_entrenadores.setLocationRelativeTo(this);
        jd_entrenadores.setVisible(true);
    }
    
    private void abrePreparadores() {
        this.setVisible(false);
        jd_preparadores.setModal(true);
        jd_preparadores.pack();
        jd_preparadores.setLocationRelativeTo(this);
        jd_preparadores.setVisible(true);
    }
    
    private void abrePsicologos() {
        this.setVisible(false);
        jd_psicologos.setModal(true);
        jd_psicologos.pack();
        jd_psicologos.setLocationRelativeTo(this);
        jd_psicologos.setVisible(true);
    }

    private void abreListar() {
        this.setVisible(false);
        jd_listar.setModal(true);
        jd_listar.pack();
        jd_listar.setLocationRelativeTo(this);
        jd_listar.setVisible(true);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Especialidad;
    private javax.swing.JTextField apellidoTxt;
    private javax.swing.JTextField apellidoTxt1;
    private javax.swing.JTextField apellidoTxt2;
    private javax.swing.JTextField apellidoTxt3;
    private javax.swing.JTextField atendidosTxt;
    private javax.swing.JButton butt_cancel;
    private javax.swing.JButton butt_cancel1;
    private javax.swing.JButton butt_cancel2;
    private javax.swing.JButton butt_cancel3;
    private javax.swing.JButton butt_crear;
    private javax.swing.JButton butt_guardar;
    private javax.swing.JButton butt_guardar1;
    private javax.swing.JButton butt_guardar2;
    private javax.swing.JButton butt_guardar3;
    private javax.swing.JComboBox<String> cb_personas;
    private javax.swing.JTextField contratoTxt;
    private javax.swing.JTextField contratoTxt1;
    private javax.swing.JTextField contratoTxt2;
    private javax.swing.JTextField copasTxt;
    private javax.swing.JTextField copasTxt1;
    private javax.swing.JSpinner edadTxt;
    private javax.swing.JSpinner edadTxt1;
    private javax.swing.JSpinner edadTxt2;
    private javax.swing.JSpinner edadTxt3;
    private javax.swing.JTextField especialidadTxt;
    private javax.swing.JTextField especialidadTxt1;
    private javax.swing.JTextField idTxt;
    private javax.swing.JTextField idTxt1;
    private javax.swing.JTextField informesTxt1;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_entrenadores;
    private javax.swing.JDialog jd_jugadores;
    private javax.swing.JDialog jd_listar;
    private javax.swing.JDialog jd_preparadores;
    private javax.swing.JDialog jd_psicologos;
    private javax.swing.JTable jt_lista;
    private javax.swing.JTree jt_personas;
    private javax.swing.JTextField jugadasTxt;
    private javax.swing.JPopupMenu menu_popup;
    private javax.swing.JTextField nacionalidadTxt;
    private javax.swing.JTextField nacionalidadTxt1;
    private javax.swing.JTextField nacionalidadTxt2;
    private javax.swing.JTextField nacionalidadTxt3;
    private javax.swing.JTextField nombreTxt;
    private javax.swing.JTextField nombreTxt1;
    private javax.swing.JTextField nombreTxt2;
    private javax.swing.JTextField nombreTxt3;
    private javax.swing.JTextField numeroTxt;
    private javax.swing.JMenuItem opcion_eliminar;
    private javax.swing.JMenuItem opcion_listar;
    private javax.swing.JMenuItem opcion_modificar;
    private javax.swing.JTextField tarjetasTxt;
    private javax.swing.JTextField tituloTxt;
    private javax.swing.JTextField tituloTxt1;
    // End of variables declaration//GEN-END:variables

    DefaultMutableTreeNode nodo_seleccionado;
    Persona persona_seleccionada;

    ArrayList<Persona> personas = new ArrayList();
}
